export const qita = {data:{
    name:'其他',
    
  },
  children:[],
  childrenThree:[{craftList:[
    {
        "colorList": [
            {
                "groupId": 7162,
                "status": 1,
                "selectType": null,
                "code": "ZJGY_TJ_TJ_JS",
                "multiple": null,
                "remark": null,
                "suffix": null,
                "prefix": null,
                "inputTips": null,
                "defaultValue": null,
                "actualValue": "烫金1:Foil 金色",
                "name": "金色",
                "sortOrder": 1,
                "whereBindId": null,
                "whereGoodsId": null,
                "maxValue": null,
                "minValue": null,
                "id": 31524
            },
            {
                "groupId": 7162,
                "status": 1,
                "selectType": null,
                "code": "ZJGY_TJ_TJ_QJ",
                "multiple": null,
                "remark": null,
                "suffix": null,
                "prefix": null,
                "inputTips": null,
                "defaultValue": null,
                "actualValue": "烫金1:Foil 浅金",
                "name": "浅金",
                "sortOrder": 2,
                "whereBindId": null,
                "whereGoodsId": null,
                "maxValue": null,
                "minValue": null,
                "id": 31525
            },
            {
                "groupId": 7162,
                "status": 1,
                "selectType": null,
                "code": "ZJGY_TJ_TJ_YJ",
                "multiple": null,
                "remark": null,
                "suffix": null,
                "prefix": null,
                "inputTips": null,
                "defaultValue": null,
                "actualValue": "烫金1:Foil 哑金",
                "name": "哑金",
                "sortOrder": 3,
                "whereBindId": null,
                "whereGoodsId": null,
                "maxValue": null,
                "minValue": null,
                "id": 31526
            },
            {
                "groupId": 7162,
                "status": 1,
                "selectType": null,
                "code": "ZJGY_TJ_TJ_HJ",
                "multiple": null,
                "remark": null,
                "suffix": null,
                "prefix": null,
                "inputTips": null,
                "defaultValue": null,
                "actualValue": "烫金1:Foil 红金",
                "name": "红金",
                "sortOrder": 4,
                "whereBindId": null,
                "whereGoodsId": null,
                "maxValue": null,
                "minValue": null,
                "id": 31527
            },
            {
                "groupId": 7162,
                "status": 1,
                "selectType": null,
                "code": "ZJGY_TJ_TJ_LJ",
                "multiple": null,
                "remark": null,
                "suffix": null,
                "prefix": null,
                "inputTips": null,
                "defaultValue": null,
                "actualValue": "烫金1:Foil 蓝金",
                "name": "蓝金",
                "sortOrder": 5,
                "whereBindId": null,
                "whereGoodsId": null,
                "maxValue": null,
                "minValue": null,
                "id": 31528
            },
            {
                "groupId": 7162,
                "status": 1,
                "selectType": null,
                "code": "ZJGY_TJ_TJ_LJ",
                "multiple": null,
                "remark": null,
                "suffix": null,
                "prefix": null,
                "inputTips": null,
                "defaultValue": null,
                "actualValue": "烫金1:Foil 绿金",
                "name": "绿金",
                "sortOrder": 6,
                "whereBindId": null,
                "whereGoodsId": null,
                "maxValue": null,
                "minValue": null,
                "id": 31529
            },
            {
                "groupId": 7162,
                "status": 1,
                "selectType": null,
                "code": "ZJGY_TJ_TJ_ZJ",
                "multiple": null,
                "remark": null,
                "suffix": null,
                "prefix": null,
                "inputTips": null,
                "defaultValue": null,
                "actualValue": "烫金1:Foil 紫金",
                "name": "紫金",
                "sortOrder": 7,
                "whereBindId": null,
                "whereGoodsId": null,
                "maxValue": null,
                "minValue": null,
                "id": 31530
            },
            {
                "groupId": 7162,
                "status": 1,
                "selectType": null,
                "code": "ZJGY_TJ_TJ_HJ",
                "multiple": null,
                "remark": null,
                "suffix": null,
                "prefix": null,
                "inputTips": null,
                "defaultValue": null,
                "actualValue": "烫金1:Foil 黑金",
                "name": "黑金",
                "sortOrder": 8,
                "whereBindId": null,
                "whereGoodsId": null,
                "maxValue": null,
                "minValue": null,
                "id": 31531
            },
            {
                "groupId": 7162,
                "status": 1,
                "selectType": null,
                "code": "ZJGY_TJ_TJ_FJ",
                "multiple": null,
                "remark": null,
                "suffix": null,
                "prefix": null,
                "inputTips": null,
                "defaultValue": null,
                "actualValue": "烫金1:Foil 粉金",
                "name": "粉金",
                "sortOrder": 9,
                "whereBindId": null,
                "whereGoodsId": null,
                "maxValue": null,
                "minValue": null,
                "id": 31532
            },
            {
                "groupId": 7162,
                "status": 1,
                "selectType": null,
                "code": "ZJGY_TJ_TJ_YS",
                "multiple": null,
                "remark": null,
                "suffix": null,
                "prefix": null,
                "inputTips": null,
                "defaultValue": null,
                "actualValue": "烫金1:Foil 银色",
                "name": "银色",
                "sortOrder": 10,
                "whereBindId": null,
                "whereGoodsId": null,
                "maxValue": null,
                "minValue": null,
                "id": 31533
            },
            {
                "groupId": 7162,
                "status": 1,
                "selectType": null,
                "code": "ZJGY_TJ_TJ_YY",
                "multiple": null,
                "remark": null,
                "suffix": null,
                "prefix": null,
                "inputTips": null,
                "defaultValue": null,
                "actualValue": "烫金1:Foil 哑银",
                "name": "哑银",
                "sortOrder": 11,
                "whereBindId": null,
                "whereGoodsId": null,
                "maxValue": null,
                "minValue": null,
                "id": 31534
            },
            {
                "groupId": 7162,
                "status": 1,
                "selectType": null,
                "code": "ZJGY_TJ_TJ_LSY",
                "multiple": null,
                "remark": null,
                "suffix": null,
                "prefix": null,
                "inputTips": null,
                "defaultValue": null,
                "actualValue": "烫金1:Foil 镭射银",
                "name": "镭射银",
                "sortOrder": 12,
                "whereBindId": null,
                "whereGoodsId": null,
                "maxValue": null,
                "minValue": null,
                "id": 31535
            },
            {
                "groupId": 7162,
                "status": 1,
                "selectType": null,
                "code": "ZJGY_TJ_TJ_QTJL",
                "multiple": null,
                "remark": null,
                "suffix": null,
                "prefix": null,
                "inputTips": null,
                "defaultValue": null,
                "actualValue": "烫金1:Foil 其它金料",
                "name": "其它金料",
                "sortOrder": 13,
                "whereBindId": null,
                "whereGoodsId": null,
                "maxValue": null,
                "minValue": null,
                "id": 31536
            }
        ],
        "id": null,
        "craftName": "烫金",
        "boxtype": 1,
        "priceName": "烫金",
        "price": null,
        "orderType": null,
        "paperId": 43,
        "isDelete": null,
        "sort": null
    },
    {
        "colorList": null,
        "id": null,
        "craftName": "击凸",
        "boxtype": 1,
        "priceName": "击凸",
        "price": null,
        "orderType": null,
        "paperId": 43,
        "isDelete": null,
        "sort": null
    },
    {
        "colorList": null,
        "id": null,
        "craftName": "局部UV",
        "boxtype": 1,
        "priceName": "局部UV",
        "price": null,
        "orderType": null,
        "paperId": 43,
        "isDelete": null,
        "sort": null
    },
    {
        "colorList": null,
        "id": null,
        "craftName": "贴窗",
        "boxtype": 1,
        "priceName": "贴窗",
        "price": null,
        "orderType": null,
        "paperId": 43,
        "isDelete": null,
        "sort": null
    },
    {
        "colorList": null,
        "id": null,
        "craftName": "击凹",
        "boxtype": 1,
        "priceName": "击凹",
        "price": null,
        "orderType": null,
        "paperId": 43,
        "isDelete": null,
        "sort": null
    }
]}]}