export const code = [
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 1,
    actionName: '起点页面',
    channel: 100000,
    channelName: '公司介绍',
    boxId: '',
    goodsId: '',
    type: '一级触点'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 1,
    actionName: '下单须知',
    channel: 101000,
    channelName: '下单须知',
    boxId: '',
    goodsId: '',
    type: '一级触点'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 1,
    actionName: '联系客服',
    channel: 102000,
    channelName: '联系客服',
    boxId: '',
    goodsId: '',
    type: '一级触点'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 1,
    actionName: '起点页面',
    channel: 200000,
    channelName: '下载刀模-卡纸盒',
    boxId: '',
    goodsId: '',
    type: '一级触点'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 1,
    actionName: '起点页面',
    channel: 201000,
    channelName: '下载刀模-微坑盒',
    boxId: '',
    goodsId: '',
    type: '一级触点'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 1,
    actionName: '起点页面',
    channel: 300000,
    channelName: '3D软打样-卡纸盒',
    boxId: '',
    goodsId: '',
    type: '一级触点'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 1,
    actionName: '起点页面',
    channel: 301000,
    channelName: '3D软打样-微坑盒',
    boxId: '',
    goodsId: '',
    type: '一级触点'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 1,
    actionName: '起点页面',
    channel: 400000,
    channelName: '拼版计价-卡纸盒',
    boxId: '',
    goodsId: '',
    type: '一级触点'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 1,
    actionName: '起点页面',
    channel: 401000,
    channelName: '拼版计价-微坑盒',
    boxId: '',
    goodsId: '',
    type: '一级触点'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 1,
    actionName: '起点页面',
    channel: 500000,
    channelName: '专版报价-卡纸盒',
    boxId: '',
    goodsId: '',
    type: '一级触点'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 1,
    actionName: '起点页面',
    channel: 501000,
    channelName: '专版报价-微坑盒',
    boxId: '',
    goodsId: '',
    type: '一级触点'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 1,
    actionName: '起点页面',
    channel: 502000,
    channelName: '专版报价-精装盒',
    boxId: '',
    goodsId: '',
    type: '一级触点'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 1,
    actionName: '起点页面',
    channel: 600000,
    channelName: '拼版报价-卡纸盒',
    boxId: '',
    goodsId: '',
    type: '一级触点'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 1,
    actionName: '起点页面',
    channel: 601000,
    channelName: '拼版报价-坑纸内托',
    boxId: '',
    goodsId: '',
    type: '一级触点'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 1,
    actionName: '起点页面',
    channel: 700000,
    channelName: '个人中心',
    boxId: '',
    goodsId: '',
    type: '一级触点'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 1,
    actionName: '起点页面',
    channel: 800000,
    channelName: '购物车-拼版购物车',
    boxId: '',
    goodsId: '',
    type: '一级触点'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 1,
    actionName: '起点页面',
    channel: 801000,
    channelName: '购物车-买纸购物车',
    boxId: '',
    goodsId: '',
    type: '一级触点'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 1,
    actionName: '起点页面',
    channel: 900000,
    channelName: '印刷加工单',
    boxId: '',
    goodsId: '',
    type: '一级触点'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 1,
    actionName: '选择盒型',
    channel: 200100,
    channelName: '下载刀模-卡纸盒-双插盒',
    boxId: 15,
    goodsId: 938,
    type: '下载刀模'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 2,
    actionName: '输入尺寸提交',
    channel: 200100,
    channelName: '下载刀模-卡纸盒-双插盒',
    boxId: 15,
    goodsId: 938,
    type: '下载刀模'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 3,
    actionName: '下载刀模提交',
    channel: 200100,
    channelName: '下载刀模-卡纸盒-双插盒',
    boxId: 15,
    goodsId: 938,
    type: '下载刀模'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 1,
    actionName: '选择盒型',
    channel: 200200,
    channelName: '下载刀模-卡纸盒-锁底盒',
    boxId: 16,
    goodsId: 939,
    type: '下载刀模'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 2,
    actionName: '输入尺寸提交',
    channel: 200200,
    channelName: '下载刀模-卡纸盒-锁底盒',
    boxId: 16,
    goodsId: 939,
    type: '下载刀模'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 3,
    actionName: '下载刀模提交',
    channel: 200200,
    channelName: '下载刀模-卡纸盒-锁底盒',
    boxId: 16,
    goodsId: 939,
    type: '下载刀模'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 1,
    actionName: '选择盒型',
    channel: 200300,
    channelName: '下载刀模-卡纸盒-自动锁底盒',
    boxId: 17,
    goodsId: 940,
    type: '下载刀模'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 2,
    actionName: '输入尺寸提交',
    channel: 200300,
    channelName: '下载刀模-卡纸盒-自动锁底盒',
    boxId: 17,
    goodsId: 940,
    type: '下载刀模'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 3,
    actionName: '下载刀模提交',
    channel: 200300,
    channelName: '下载刀模-卡纸盒-自动锁底盒',
    boxId: 17,
    goodsId: 940,
    type: '下载刀模'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 1,
    actionName: '选择盒型',
    channel: 200400,
    channelName: '下载刀模-卡纸盒-平粘盒',
    boxId: 18,
    goodsId: 941,
    type: '下载刀模'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 2,
    actionName: '输入尺寸提交',
    channel: 200400,
    channelName: '下载刀模-卡纸盒-平粘盒',
    boxId: 18,
    goodsId: 941,
    type: '下载刀模'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 3,
    actionName: '下载刀模提交',
    channel: 200400,
    channelName: '下载刀模-卡纸盒-平粘盒',
    boxId: 18,
    goodsId: 941,
    type: '下载刀模'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 1,
    actionName: '选择盒型',
    channel: 200500,
    channelName: '下载刀模-卡纸盒-一体成型盒',
    boxId: 19,
    goodsId: 942,
    type: '下载刀模'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 2,
    actionName: '输入尺寸提交',
    channel: 200500,
    channelName: '下载刀模-卡纸盒-一体成型盒',
    boxId: 19,
    goodsId: 942,
    type: '下载刀模'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 3,
    actionName: '下载刀模提交',
    channel: 200500,
    channelName: '下载刀模-卡纸盒-一体成型盒',
    boxId: 19,
    goodsId: 942,
    type: '下载刀模'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 1,
    actionName: '选择盒型',
    channel: 200600,
    channelName: '下载刀模-卡纸盒-抽屉盒',
    boxId: 20,
    goodsId: 943,
    type: '下载刀模'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 2,
    actionName: '输入尺寸提交',
    channel: 200600,
    channelName: '下载刀模-卡纸盒-抽屉盒',
    boxId: 20,
    goodsId: 943,
    type: '下载刀模'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 3,
    actionName: '下载刀模提交',
    channel: 200600,
    channelName: '下载刀模-卡纸盒-抽屉盒',
    boxId: 20,
    goodsId: 943,
    type: '下载刀模'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 1,
    actionName: '选择盒型',
    channel: 200700,
    channelName: '下载刀模-卡纸盒-天地盒',
    boxId: 21,
    goodsId: 944,
    type: '下载刀模'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 2,
    actionName: '输入尺寸提交',
    channel: 200700,
    channelName: '下载刀模-卡纸盒-天地盒',
    boxId: 21,
    goodsId: 944,
    type: '下载刀模'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 3,
    actionName: '下载刀模提交',
    channel: 200700,
    channelName: '下载刀模-卡纸盒-天地盒',
    boxId: 21,
    goodsId: 944,
    type: '下载刀模'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 1,
    actionName: '选择盒型',
    channel: 200800,
    channelName: '下载刀模-卡纸盒-吊口盒',
    boxId: 22,
    goodsId: 950,
    type: '下载刀模'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 2,
    actionName: '输入尺寸提交',
    channel: 200800,
    channelName: '下载刀模-卡纸盒-吊口盒',
    boxId: 22,
    goodsId: 950,
    type: '下载刀模'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 3,
    actionName: '下载刀模提交',
    channel: 200800,
    channelName: '下载刀模-卡纸盒-吊口盒',
    boxId: 22,
    goodsId: 950,
    type: '下载刀模'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 1,
    actionName: '选择盒型',
    channel: 201100,
    channelName: '下载刀模-微坑盒-双插盒',
    boxId: 25,
    goodsId: 945,
    type: '下载刀模'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 2,
    actionName: '输入尺寸提交',
    channel: 201100,
    channelName: '下载刀模-微坑盒-双插盒',
    boxId: 25,
    goodsId: 945,
    type: '下载刀模'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 3,
    actionName: '下载刀模提交',
    channel: 201100,
    channelName: '下载刀模-微坑盒-双插盒',
    boxId: 25,
    goodsId: 945,
    type: '下载刀模'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 1,
    actionName: '选择盒型',
    channel: 201200,
    channelName: '下载刀模-微坑盒-锁底盒',
    boxId: 26,
    goodsId: 946,
    type: '下载刀模'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 2,
    actionName: '输入尺寸提交',
    channel: 201200,
    channelName: '下载刀模-微坑盒-锁底盒',
    boxId: 26,
    goodsId: 946,
    type: '下载刀模'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 3,
    actionName: '下载刀模提交',
    channel: 201200,
    channelName: '下载刀模-微坑盒-锁底盒',
    boxId: 26,
    goodsId: 946,
    type: '下载刀模'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 1,
    actionName: '选择盒型',
    channel: 201300,
    channelName: '下载刀模-微坑盒-自动锁底盒',
    boxId: 79,
    goodsId: '',
    type: '下载刀模'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 2,
    actionName: '输入尺寸提交',
    channel: 201300,
    channelName: '下载刀模-微坑盒-自动锁底盒',
    boxId: 79,
    goodsId: '',
    type: '下载刀模'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 3,
    actionName: '下载刀模提交',
    channel: 201300,
    channelName: '下载刀模-微坑盒-自动锁底盒',
    boxId: 79,
    goodsId: '',
    type: '下载刀模'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 1,
    actionName: '选择盒型',
    channel: 201400,
    channelName: '下载刀模-微坑盒-一体成型盒',
    boxId: 28,
    goodsId: 948,
    type: '下载刀模'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 2,
    actionName: '输入尺寸提交',
    channel: 201400,
    channelName: '下载刀模-微坑盒-一体成型盒',
    boxId: 28,
    goodsId: 948,
    type: '下载刀模'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 3,
    actionName: '下载刀模提交',
    channel: 201400,
    channelName: '下载刀模-微坑盒-一体成型盒',
    boxId: 28,
    goodsId: 948,
    type: '下载刀模'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 1,
    actionName: '选择盒型',
    channel: 201500,
    channelName: '下载刀模-微坑盒-手提盒',
    boxId: 29,
    goodsId: '',
    type: '下载刀模'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 2,
    actionName: '输入尺寸提交',
    channel: 201500,
    channelName: '下载刀模-微坑盒-手提盒',
    boxId: 29,
    goodsId: '',
    type: '下载刀模'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 3,
    actionName: '下载刀模提交',
    channel: 201500,
    channelName: '下载刀模-微坑盒-手提盒',
    boxId: 29,
    goodsId: '',
    type: '下载刀模'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 1,
    actionName: '选择盒型',
    channel: 201600,
    channelName: '下载刀模-微坑盒-天地盒',
    boxId: 30,
    goodsId: '',
    type: '下载刀模'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 2,
    actionName: '输入尺寸提交',
    channel: 201600,
    channelName: '下载刀模-微坑盒-天地盒',
    boxId: 30,
    goodsId: '',
    type: '下载刀模'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 3,
    actionName: '下载刀模提交',
    channel: 201600,
    channelName: '下载刀模-微坑盒-天地盒',
    boxId: 30,
    goodsId: '',
    type: '下载刀模'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 1,
    actionName: '选择盒型',
    channel: 201700,
    channelName: '下载刀模-微坑盒-吊口盒',
    boxId: 76,
    goodsId: 711,
    type: '下载刀模'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 2,
    actionName: '输入尺寸提交',
    channel: 201700,
    channelName: '下载刀模-微坑盒-吊口盒',
    boxId: 76,
    goodsId: 711,
    type: '下载刀模'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 3,
    actionName: '下载刀模提交',
    channel: 201700,
    channelName: '下载刀模-微坑盒-吊口盒',
    boxId: 76,
    goodsId: 711,
    type: '下载刀模'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 1,
    actionName: '选择盒型',
    channel: 300100,
    channelName: '软打样-卡纸盒-双插盒',
    boxId: 15,
    goodsId: 938,
    type: '3D软打样'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 2,
    actionName: '提交平面设计图',
    channel: 300100,
    channelName: '软打样-卡纸盒-双插盒',
    boxId: 15,
    goodsId: 938,
    type: '3D软打样'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 3,
    actionName: '生成分享链接',
    channel: 300100,
    channelName: '软打样-卡纸盒-双插盒',
    boxId: 15,
    goodsId: 938,
    type: '3D软打样'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 1,
    actionName: '选择盒型',
    channel: 300200,
    channelName: '软打样-卡纸盒-锁底盒',
    boxId: 16,
    goodsId: 939,
    type: '3D软打样'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 2,
    actionName: '提交平面设计图',
    channel: 300200,
    channelName: '软打样-卡纸盒-锁底盒',
    boxId: 16,
    goodsId: 939,
    type: '3D软打样'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 3,
    actionName: '生成分享链接',
    channel: 300200,
    channelName: '软打样-卡纸盒-锁底盒',
    boxId: 16,
    goodsId: 939,
    type: '3D软打样'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 1,
    actionName: '选择盒型',
    channel: 300300,
    channelName: '软打样-卡纸盒-自动锁底盒',
    boxId: 17,
    goodsId: 940,
    type: '3D软打样'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 2,
    actionName: '提交平面设计图',
    channel: 300300,
    channelName: '软打样-卡纸盒-自动锁底盒',
    boxId: 17,
    goodsId: 940,
    type: '3D软打样'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 3,
    actionName: '生成分享链接',
    channel: 300300,
    channelName: '软打样-卡纸盒-自动锁底盒',
    boxId: 17,
    goodsId: 940,
    type: '3D软打样'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 1,
    actionName: '选择盒型',
    channel: 300400,
    channelName: '软打样-卡纸盒-平粘盒',
    boxId: 18,
    goodsId: 941,
    type: '3D软打样'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 2,
    actionName: '提交平面设计图',
    channel: 300400,
    channelName: '软打样-卡纸盒-平粘盒',
    boxId: 18,
    goodsId: 941,
    type: '3D软打样'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 3,
    actionName: '生成分享链接',
    channel: 300400,
    channelName: '软打样-卡纸盒-平粘盒',
    boxId: 18,
    goodsId: 941,
    type: '3D软打样'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 1,
    actionName: '选择盒型',
    channel: 300500,
    channelName: '软打样-卡纸盒-一体成型盒',
    boxId: 19,
    goodsId: 942,
    type: '3D软打样'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 2,
    actionName: '提交平面设计图',
    channel: 300500,
    channelName: '软打样-卡纸盒-一体成型盒',
    boxId: 19,
    goodsId: 942,
    type: '3D软打样'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 3,
    actionName: '生成分享链接',
    channel: 300500,
    channelName: '软打样-卡纸盒-一体成型盒',
    boxId: 19,
    goodsId: 942,
    type: '3D软打样'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 1,
    actionName: '选择盒型',
    channel: 300600,
    channelName: '软打样-卡纸盒-抽屉盒',
    boxId: 20,
    goodsId: 943,
    type: '3D软打样'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 2,
    actionName: '提交平面设计图',
    channel: 300600,
    channelName: '软打样-卡纸盒-抽屉盒',
    boxId: 20,
    goodsId: 943,
    type: '3D软打样'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 3,
    actionName: '生成分享链接',
    channel: 300600,
    channelName: '软打样-卡纸盒-抽屉盒',
    boxId: 20,
    goodsId: 943,
    type: '3D软打样'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 1,
    actionName: '选择盒型',
    channel: 300700,
    channelName: '软打样-卡纸盒-天地盒',
    boxId: 21,
    goodsId: 944,
    type: '3D软打样'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 2,
    actionName: '提交平面设计图',
    channel: 300700,
    channelName: '软打样-卡纸盒-天地盒',
    boxId: 21,
    goodsId: 944,
    type: '3D软打样'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 3,
    actionName: '生成分享链接',
    channel: 300700,
    channelName: '软打样-卡纸盒-天地盒',
    boxId: 21,
    goodsId: 944,
    type: '3D软打样'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 1,
    actionName: '选择盒型',
    channel: 300800,
    channelName: '软打样-卡纸盒-吊口盒',
    boxId: 22,
    goodsId: 950,
    type: '3D软打样'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 2,
    actionName: '提交平面设计图',
    channel: 300800,
    channelName: '软打样-卡纸盒-吊口盒',
    boxId: 22,
    goodsId: 950,
    type: '3D软打样'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 3,
    actionName: '生成分享链接',
    channel: 300800,
    channelName: '软打样-卡纸盒-吊口盒',
    boxId: 22,
    goodsId: 950,
    type: '3D软打样'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 1,
    actionName: '选择盒型',
    channel: 301100,
    channelName: '软打样-微坑盒-双插盒',
    boxId: 25,
    goodsId: 945,
    type: '3D软打样'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 2,
    actionName: '提交平面设计图',
    channel: 301100,
    channelName: '软打样-微坑盒-双插盒',
    boxId: 25,
    goodsId: 945,
    type: '3D软打样'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 3,
    actionName: '生成分享链接',
    channel: 301100,
    channelName: '软打样-微坑盒-双插盒',
    boxId: 25,
    goodsId: 945,
    type: '3D软打样'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 1,
    actionName: '选择盒型',
    channel: 301200,
    channelName: '软打样-微坑盒-锁底盒',
    boxId: 26,
    goodsId: 946,
    type: '3D软打样'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 2,
    actionName: '提交平面设计图',
    channel: 301200,
    channelName: '软打样-微坑盒-锁底盒',
    boxId: 26,
    goodsId: 946,
    type: '3D软打样'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 3,
    actionName: '生成分享链接',
    channel: 301200,
    channelName: '软打样-微坑盒-锁底盒',
    boxId: 26,
    goodsId: 946,
    type: '3D软打样'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 1,
    actionName: '选择盒型',
    channel: 301300,
    channelName: '软打样-微坑盒-自动锁底盒',
    boxId: 79,
    goodsId: '',
    type: '3D软打样'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 2,
    actionName: '提交平面设计图',
    channel: 301300,
    channelName: '软打样-微坑盒-自动锁底盒',
    boxId: 79,
    goodsId: '',
    type: '3D软打样'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 3,
    actionName: '生成分享链接',
    channel: 301300,
    channelName: '软打样-微坑盒-自动锁底盒',
    boxId: 79,
    goodsId: '',
    type: '3D软打样'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 1,
    actionName: '选择盒型',
    channel: 301400,
    channelName: '软打样-微坑盒-一体成型盒',
    boxId: 28,
    goodsId: 948,
    type: '3D软打样'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 2,
    actionName: '提交平面设计图',
    channel: 301400,
    channelName: '软打样-微坑盒-一体成型盒',
    boxId: 28,
    goodsId: 948,
    type: '3D软打样'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 3,
    actionName: '生成分享链接',
    channel: 301400,
    channelName: '软打样-微坑盒-一体成型盒',
    boxId: 28,
    goodsId: 948,
    type: '3D软打样'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 1,
    actionName: '选择盒型',
    channel: 301500,
    channelName: '软打样-微坑盒-手提盒',
    boxId: 29,
    goodsId: '',
    type: '3D软打样'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 2,
    actionName: '提交平面设计图',
    channel: 301500,
    channelName: '软打样-微坑盒-手提盒',
    boxId: 29,
    goodsId: '',
    type: '3D软打样'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 3,
    actionName: '生成分享链接',
    channel: 301500,
    channelName: '软打样-微坑盒-手提盒',
    boxId: 29,
    goodsId: '',
    type: '3D软打样'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 1,
    actionName: '选择盒型',
    channel: 301600,
    channelName: '软打样-微坑盒-天地盒',
    boxId: 30,
    goodsId: '',
    type: '3D软打样'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 2,
    actionName: '提交平面设计图',
    channel: 301600,
    channelName: '软打样-微坑盒-天地盒',
    boxId: 30,
    goodsId: '',
    type: '3D软打样'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 3,
    actionName: '生成分享链接',
    channel: 301600,
    channelName: '软打样-微坑盒-天地盒',
    boxId: 30,
    goodsId: '',
    type: '3D软打样'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 1,
    actionName: '选择盒型',
    channel: 301700,
    channelName: '软打样-微坑盒-吊口盒',
    boxId: 76,
    goodsId: 711,
    type: '3D软打样'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 2,
    actionName: '提交平面设计图',
    channel: 301700,
    channelName: '软打样-微坑盒-吊口盒',
    boxId: 76,
    goodsId: 711,
    type: '3D软打样'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 3,
    actionName: '生成分享链接',
    channel: 301700,
    channelName: '软打样-微坑盒-吊口盒',
    boxId: 76,
    goodsId: 711,
    type: '3D软打样'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 1,
    actionName: '选择盒型',
    channel: 400100,
    channelName: '拼版计价-卡纸盒-双插盒',
    boxId: 15,
    goodsId: 938,
    type: '拼版计价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 2,
    actionName: '输入尺寸提交',
    channel: 400100,
    channelName: '拼版计价-卡纸盒-双插盒',
    boxId: 15,
    goodsId: 938,
    type: '拼版计价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 3,
    actionName: '申请生成报价单',
    channel: 400100,
    channelName: '拼版计价-卡纸盒-双插盒',
    boxId: 15,
    goodsId: 938,
    type: '拼版计价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 4,
    actionName: '保存报价单',
    channel: 400100,
    channelName: '拼版计价-卡纸盒-双插盒',
    boxId: 15,
    goodsId: 938,
    type: '拼版计价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 1,
    actionName: '选择盒型',
    channel: 400200,
    channelName: '拼版计价-卡纸盒-锁底盒',
    boxId: 16,
    goodsId: 939,
    type: '拼版计价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 2,
    actionName: '输入尺寸提交',
    channel: 400200,
    channelName: '拼版计价-卡纸盒-锁底盒',
    boxId: 16,
    goodsId: 939,
    type: '拼版计价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 3,
    actionName: '申请生成报价单',
    channel: 400200,
    channelName: '拼版计价-卡纸盒-锁底盒',
    boxId: 16,
    goodsId: 939,
    type: '拼版计价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 4,
    actionName: '保存报价单',
    channel: 400200,
    channelName: '拼版计价-卡纸盒-锁底盒',
    boxId: 16,
    goodsId: 939,
    type: '拼版计价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 1,
    actionName: '选择盒型',
    channel: 400300,
    channelName: '拼版计价-卡纸盒-自动锁底盒',
    boxId: 17,
    goodsId: 940,
    type: '拼版计价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 2,
    actionName: '输入尺寸提交',
    channel: 400300,
    channelName: '拼版计价-卡纸盒-自动锁底盒',
    boxId: 17,
    goodsId: 940,
    type: '拼版计价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 3,
    actionName: '申请生成报价单',
    channel: 400300,
    channelName: '拼版计价-卡纸盒-自动锁底盒',
    boxId: 17,
    goodsId: 940,
    type: '拼版计价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 4,
    actionName: '保存报价单',
    channel: 400300,
    channelName: '拼版计价-卡纸盒-自动锁底盒',
    boxId: 17,
    goodsId: 940,
    type: '拼版计价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 1,
    actionName: '选择盒型',
    channel: 400400,
    channelName: '拼版计价-卡纸盒-平粘盒',
    boxId: 18,
    goodsId: 941,
    type: '拼版计价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 2,
    actionName: '输入尺寸提交',
    channel: 400400,
    channelName: '拼版计价-卡纸盒-平粘盒',
    boxId: 18,
    goodsId: 941,
    type: '拼版计价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 3,
    actionName: '申请生成报价单',
    channel: 400400,
    channelName: '拼版计价-卡纸盒-平粘盒',
    boxId: 18,
    goodsId: 941,
    type: '拼版计价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 4,
    actionName: '保存报价单',
    channel: 400400,
    channelName: '拼版计价-卡纸盒-平粘盒',
    boxId: 18,
    goodsId: 941,
    type: '拼版计价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 1,
    actionName: '选择盒型',
    channel: 400500,
    channelName: '拼版计价-卡纸盒-一体成型盒',
    boxId: 19,
    goodsId: 942,
    type: '拼版计价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 2,
    actionName: '输入尺寸提交',
    channel: 400500,
    channelName: '拼版计价-卡纸盒-一体成型盒',
    boxId: 19,
    goodsId: 942,
    type: '拼版计价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 3,
    actionName: '申请生成报价单',
    channel: 400500,
    channelName: '拼版计价-卡纸盒-一体成型盒',
    boxId: 19,
    goodsId: 942,
    type: '拼版计价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 4,
    actionName: '保存报价单',
    channel: 400500,
    channelName: '拼版计价-卡纸盒-一体成型盒',
    boxId: 19,
    goodsId: 942,
    type: '拼版计价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 1,
    actionName: '选择盒型',
    channel: 400600,
    channelName: '拼版计价-卡纸盒-抽屉盒',
    boxId: 20,
    goodsId: 943,
    type: '拼版计价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 2,
    actionName: '输入尺寸提交',
    channel: 400600,
    channelName: '拼版计价-卡纸盒-抽屉盒',
    boxId: 20,
    goodsId: 943,
    type: '拼版计价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 3,
    actionName: '申请生成报价单',
    channel: 400600,
    channelName: '拼版计价-卡纸盒-抽屉盒',
    boxId: 20,
    goodsId: 943,
    type: '拼版计价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 4,
    actionName: '保存报价单',
    channel: 400600,
    channelName: '拼版计价-卡纸盒-抽屉盒',
    boxId: 20,
    goodsId: 943,
    type: '拼版计价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 1,
    actionName: '选择盒型',
    channel: 400700,
    channelName: '拼版计价-卡纸盒-天地盒',
    boxId: 21,
    goodsId: 944,
    type: '拼版计价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 2,
    actionName: '输入尺寸提交',
    channel: 400700,
    channelName: '拼版计价-卡纸盒-天地盒',
    boxId: 21,
    goodsId: 944,
    type: '拼版计价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 3,
    actionName: '申请生成报价单',
    channel: 400700,
    channelName: '拼版计价-卡纸盒-天地盒',
    boxId: 21,
    goodsId: 944,
    type: '拼版计价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 4,
    actionName: '保存报价单',
    channel: 400700,
    channelName: '拼版计价-卡纸盒-天地盒',
    boxId: 21,
    goodsId: 944,
    type: '拼版计价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 1,
    actionName: '选择盒型',
    channel: 400800,
    channelName: '拼版计价-卡纸盒-吊口盒',
    boxId: 22,
    goodsId: 950,
    type: '拼版计价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 2,
    actionName: '输入尺寸提交',
    channel: 400800,
    channelName: '拼版计价-卡纸盒-吊口盒',
    boxId: 22,
    goodsId: 950,
    type: '拼版计价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 3,
    actionName: '申请生成报价单',
    channel: 400800,
    channelName: '拼版计价-卡纸盒-吊口盒',
    boxId: 22,
    goodsId: 950,
    type: '拼版计价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 4,
    actionName: '保存报价单',
    channel: 400800,
    channelName: '拼版计价-卡纸盒-吊口盒',
    boxId: 22,
    goodsId: 950,
    type: '拼版计价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 1,
    actionName: '选择盒型',
    channel: 401100,
    channelName: '拼版计价-微坑盒-双插盒',
    boxId: 25,
    goodsId: 945,
    type: '拼版计价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 2,
    actionName: '输入尺寸提交',
    channel: 401100,
    channelName: '拼版计价-微坑盒-双插盒',
    boxId: 25,
    goodsId: 945,
    type: '拼版计价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 3,
    actionName: '申请生成报价单',
    channel: 401100,
    channelName: '拼版计价-微坑盒-双插盒',
    boxId: 25,
    goodsId: 945,
    type: '拼版计价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 4,
    actionName: '保存报价单',
    channel: 401100,
    channelName: '拼版计价-微坑盒-双插盒',
    boxId: 25,
    goodsId: 945,
    type: '拼版计价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 1,
    actionName: '选择盒型',
    channel: 401200,
    channelName: '拼版计价-微坑盒-锁底盒',
    boxId: 26,
    goodsId: 946,
    type: '拼版计价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 2,
    actionName: '输入尺寸提交',
    channel: 401200,
    channelName: '拼版计价-微坑盒-锁底盒',
    boxId: 26,
    goodsId: 946,
    type: '拼版计价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 3,
    actionName: '申请生成报价单',
    channel: 401200,
    channelName: '拼版计价-微坑盒-锁底盒',
    boxId: 26,
    goodsId: 946,
    type: '拼版计价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 4,
    actionName: '保存报价单',
    channel: 401200,
    channelName: '拼版计价-微坑盒-锁底盒',
    boxId: 26,
    goodsId: 946,
    type: '拼版计价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 1,
    actionName: '选择盒型',
    channel: 401300,
    channelName: '拼版计价-微坑盒-自动锁底盒',
    boxId: 79,
    goodsId: '',
    type: '拼版计价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 2,
    actionName: '输入尺寸提交',
    channel: 401300,
    channelName: '拼版计价-微坑盒-自动锁底盒',
    boxId: 79,
    goodsId: '',
    type: '拼版计价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 3,
    actionName: '申请生成报价单',
    channel: 401300,
    channelName: '拼版计价-微坑盒-自动锁底盒',
    boxId: 79,
    goodsId: '',
    type: '拼版计价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 4,
    actionName: '保存报价单',
    channel: 401300,
    channelName: '拼版计价-微坑盒-自动锁底盒',
    boxId: 79,
    goodsId: '',
    type: '拼版计价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 1,
    actionName: '选择盒型',
    channel: 401400,
    channelName: '拼版计价-微坑盒-一体成型盒',
    boxId: 28,
    goodsId: 948,
    type: '拼版计价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 2,
    actionName: '输入尺寸提交',
    channel: 401400,
    channelName: '拼版计价-微坑盒-一体成型盒',
    boxId: 28,
    goodsId: 948,
    type: '拼版计价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 3,
    actionName: '申请生成报价单',
    channel: 401400,
    channelName: '拼版计价-微坑盒-一体成型盒',
    boxId: 28,
    goodsId: 948,
    type: '拼版计价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 4,
    actionName: '保存报价单',
    channel: 401400,
    channelName: '拼版计价-微坑盒-一体成型盒',
    boxId: 28,
    goodsId: 948,
    type: '拼版计价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 1,
    actionName: '选择盒型',
    channel: 401500,
    channelName: '拼版计价-微坑盒-手提盒',
    boxId: 29,
    goodsId: '',
    type: '拼版计价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 2,
    actionName: '输入尺寸提交',
    channel: 401500,
    channelName: '拼版计价-微坑盒-手提盒',
    boxId: 29,
    goodsId: '',
    type: '拼版计价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 3,
    actionName: '申请生成报价单',
    channel: 401500,
    channelName: '拼版计价-微坑盒-手提盒',
    boxId: 29,
    goodsId: '',
    type: '拼版计价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 4,
    actionName: '保存报价单',
    channel: 401500,
    channelName: '拼版计价-微坑盒-手提盒',
    boxId: 29,
    goodsId: '',
    type: '拼版计价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 1,
    actionName: '选择盒型',
    channel: 401600,
    channelName: '拼版计价-微坑盒-天地盒',
    boxId: 30,
    goodsId: '',
    type: '拼版计价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 2,
    actionName: '输入尺寸提交',
    channel: 401600,
    channelName: '拼版计价-微坑盒-天地盒',
    boxId: 30,
    goodsId: '',
    type: '拼版计价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 3,
    actionName: '申请生成报价单',
    channel: 401600,
    channelName: '拼版计价-微坑盒-天地盒',
    boxId: 30,
    goodsId: '',
    type: '拼版计价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 4,
    actionName: '保存报价单',
    channel: 401600,
    channelName: '拼版计价-微坑盒-天地盒',
    boxId: 30,
    goodsId: '',
    type: '拼版计价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 1,
    actionName: '选择盒型',
    channel: 401700,
    channelName: '拼版计价-微坑盒-吊口盒',
    boxId: 76,
    goodsId: 711,
    type: '拼版计价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 2,
    actionName: '输入尺寸提交',
    channel: 401700,
    channelName: '拼版计价-微坑盒-吊口盒',
    boxId: 76,
    goodsId: 711,
    type: '拼版计价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 3,
    actionName: '申请生成报价单',
    channel: 401700,
    channelName: '拼版计价-微坑盒-吊口盒',
    boxId: 76,
    goodsId: 711,
    type: '拼版计价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 4,
    actionName: '保存报价单',
    channel: 401700,
    channelName: '拼版计价-微坑盒-吊口盒',
    boxId: 76,
    goodsId: 711,
    type: '拼版计价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 1,
    actionName: '选择盒型',
    channel: 500100,
    channelName: '专版报价-卡纸盒-双插盒',
    boxId: 15,
    goodsId: 938,
    type: '专版报价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 2,
    actionName: '输入尺寸提交',
    channel: 500100,
    channelName: '专版报价-卡纸盒-双插盒',
    boxId: 15,
    goodsId: 938,
    type: '专版报价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 3,
    actionName: '加入购物车',
    channel: 500100,
    channelName: '专版报价-卡纸盒-双插盒',
    boxId: 15,
    goodsId: 938,
    type: '专版报价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 4,
    actionName: '确认下单',
    channel: 500100,
    channelName: '专版报价-卡纸盒-双插盒',
    boxId: 15,
    goodsId: 938,
    type: '专版报价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 5,
    actionName: '生成订单',
    channel: 500100,
    channelName: '专版报价-卡纸盒-双插盒',
    boxId: 15,
    goodsId: 938,
    type: '专版报价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 6,
    actionName: '支付成功',
    channel: 500100,
    channelName: '专版报价-卡纸盒-双插盒',
    boxId: 15,
    goodsId: 938,
    type: '专版报价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 1,
    actionName: '选择盒型',
    channel: 500200,
    channelName: '专版报价-卡纸盒-锁底盒',
    boxId: 16,
    goodsId: 939,
    type: '专版报价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 2,
    actionName: '输入尺寸提交',
    channel: 500200,
    channelName: '专版报价-卡纸盒-锁底盒',
    boxId: 16,
    goodsId: 939,
    type: '专版报价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 3,
    actionName: '加入购物车',
    channel: 500200,
    channelName: '专版报价-卡纸盒-锁底盒',
    boxId: 16,
    goodsId: 939,
    type: '专版报价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 4,
    actionName: '确认下单',
    channel: 500200,
    channelName: '专版报价-卡纸盒-锁底盒',
    boxId: 16,
    goodsId: 939,
    type: '专版报价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 5,
    actionName: '生成订单',
    channel: 500200,
    channelName: '专版报价-卡纸盒-锁底盒',
    boxId: 16,
    goodsId: 939,
    type: '专版报价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 6,
    actionName: '支付成功',
    channel: 500200,
    channelName: '专版报价-卡纸盒-锁底盒',
    boxId: 16,
    goodsId: 939,
    type: '专版报价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 1,
    actionName: '选择盒型',
    channel: 500300,
    channelName: '专版报价-卡纸盒-自动锁底盒',
    boxId: 17,
    goodsId: 940,
    type: '专版报价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 2,
    actionName: '输入尺寸提交',
    channel: 500300,
    channelName: '专版报价-卡纸盒-自动锁底盒',
    boxId: 17,
    goodsId: 940,
    type: '专版报价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 3,
    actionName: '加入购物车',
    channel: 500300,
    channelName: '专版报价-卡纸盒-自动锁底盒',
    boxId: 17,
    goodsId: 940,
    type: '专版报价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 4,
    actionName: '确认下单',
    channel: 500300,
    channelName: '专版报价-卡纸盒-自动锁底盒',
    boxId: 17,
    goodsId: 940,
    type: '专版报价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 5,
    actionName: '生成订单',
    channel: 500300,
    channelName: '专版报价-卡纸盒-自动锁底盒',
    boxId: 17,
    goodsId: 940,
    type: '专版报价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 6,
    actionName: '支付成功',
    channel: 500300,
    channelName: '专版报价-卡纸盒-自动锁底盒',
    boxId: 17,
    goodsId: 940,
    type: '专版报价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 1,
    actionName: '选择盒型',
    channel: 500400,
    channelName: '专版报价-卡纸盒-平粘盒',
    boxId: 18,
    goodsId: 941,
    type: '专版报价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 2,
    actionName: '输入尺寸提交',
    channel: 500400,
    channelName: '专版报价-卡纸盒-平粘盒',
    boxId: 18,
    goodsId: 941,
    type: '专版报价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 3,
    actionName: '加入购物车',
    channel: 500400,
    channelName: '专版报价-卡纸盒-平粘盒',
    boxId: 18,
    goodsId: 941,
    type: '专版报价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 4,
    actionName: '确认下单',
    channel: 500400,
    channelName: '专版报价-卡纸盒-平粘盒',
    boxId: 18,
    goodsId: 941,
    type: '专版报价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 5,
    actionName: '生成订单',
    channel: 500400,
    channelName: '专版报价-卡纸盒-平粘盒',
    boxId: 18,
    goodsId: 941,
    type: '专版报价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 6,
    actionName: '支付成功',
    channel: 500400,
    channelName: '专版报价-卡纸盒-平粘盒',
    boxId: 18,
    goodsId: 941,
    type: '专版报价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 1,
    actionName: '选择盒型',
    channel: 500500,
    channelName: '专版报价-卡纸盒-一体成型盒',
    boxId: 19,
    goodsId: 942,
    type: '专版报价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 2,
    actionName: '输入尺寸提交',
    channel: 500500,
    channelName: '专版报价-卡纸盒-一体成型盒',
    boxId: 19,
    goodsId: 942,
    type: '专版报价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 3,
    actionName: '加入购物车',
    channel: 500500,
    channelName: '专版报价-卡纸盒-一体成型盒',
    boxId: 19,
    goodsId: 942,
    type: '专版报价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 4,
    actionName: '确认下单',
    channel: 500500,
    channelName: '专版报价-卡纸盒-一体成型盒',
    boxId: 19,
    goodsId: 942,
    type: '专版报价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 5,
    actionName: '生成订单',
    channel: 500500,
    channelName: '专版报价-卡纸盒-一体成型盒',
    boxId: 19,
    goodsId: 942,
    type: '专版报价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 6,
    actionName: '支付成功',
    channel: 500500,
    channelName: '专版报价-卡纸盒-一体成型盒',
    boxId: 19,
    goodsId: 942,
    type: '专版报价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 1,
    actionName: '选择盒型',
    channel: 500600,
    channelName: '专版报价-卡纸盒-吊口盒',
    boxId: 22,
    goodsId: 950,
    type: '专版报价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 2,
    actionName: '输入尺寸提交',
    channel: 500600,
    channelName: '专版报价-卡纸盒-吊口盒',
    boxId: 22,
    goodsId: 950,
    type: '专版报价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 3,
    actionName: '加入购物车',
    channel: 500600,
    channelName: '专版报价-卡纸盒-吊口盒',
    boxId: 22,
    goodsId: 950,
    type: '专版报价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 4,
    actionName: '确认下单',
    channel: 500600,
    channelName: '专版报价-卡纸盒-吊口盒',
    boxId: 22,
    goodsId: 950,
    type: '专版报价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 5,
    actionName: '生成订单',
    channel: 500600,
    channelName: '专版报价-卡纸盒-吊口盒',
    boxId: 22,
    goodsId: 950,
    type: '专版报价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 6,
    actionName: '支付成功',
    channel: 500600,
    channelName: '专版报价-卡纸盒-吊口盒',
    boxId: 22,
    goodsId: 950,
    type: '专版报价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 1,
    actionName: '选择盒型',
    channel: 500700,
    channelName: '专版报价-卡纸盒-特殊盒型',
    boxId: '',
    goodsId: '',
    type: '专版报价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 2,
    actionName: '输入尺寸提交',
    channel: 500700,
    channelName: '专版报价-卡纸盒-特殊盒型',
    boxId: '',
    goodsId: '',
    type: '专版报价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 3,
    actionName: '加入购物车',
    channel: 500700,
    channelName: '专版报价-卡纸盒-特殊盒型',
    boxId: '',
    goodsId: '',
    type: '专版报价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 4,
    actionName: '确认下单',
    channel: 500700,
    channelName: '专版报价-卡纸盒-特殊盒型',
    boxId: '',
    goodsId: '',
    type: '专版报价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 5,
    actionName: '生成订单',
    channel: 500700,
    channelName: '专版报价-卡纸盒-特殊盒型',
    boxId: '',
    goodsId: '',
    type: '专版报价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 6,
    actionName: '支付成功',
    channel: 500700,
    channelName: '专版报价-卡纸盒-特殊盒型',
    boxId: '',
    goodsId: '',
    type: '专版报价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 1,
    actionName: '上传刀模',
    channel: 500800,
    channelName: '专版报价-卡纸盒-自定义拼版',
    boxId: '',
    goodsId: '',
    type: '专版报价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 2,
    actionName: '输入尺寸提交',
    channel: 500800,
    channelName: '专版报价-卡纸盒-自定义拼版',
    boxId: '',
    goodsId: '',
    type: '专版报价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 3,
    actionName: '加入购物车',
    channel: 500800,
    channelName: '专版报价-卡纸盒-自定义拼版',
    boxId: '',
    goodsId: '',
    type: '专版报价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 4,
    actionName: '确认下单',
    channel: 500800,
    channelName: '专版报价-卡纸盒-自定义拼版',
    boxId: '',
    goodsId: '',
    type: '专版报价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 5,
    actionName: '生成订单',
    channel: 500800,
    channelName: '专版报价-卡纸盒-自定义拼版',
    boxId: '',
    goodsId: '',
    type: '专版报价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 6,
    actionName: '支付成功',
    channel: 500800,
    channelName: '专版报价-卡纸盒-自定义拼版',
    boxId: '',
    goodsId: '',
    type: '专版报价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 1,
    actionName: '选择盒型',
    channel: 501100,
    channelName: '专版报价-微坑盒-双插盒',
    boxId: 25,
    goodsId: 945,
    type: '专版报价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 2,
    actionName: '输入尺寸提交',
    channel: 501100,
    channelName: '专版报价-微坑盒-双插盒',
    boxId: 25,
    goodsId: 945,
    type: '专版报价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 3,
    actionName: '加入购物车',
    channel: 501100,
    channelName: '专版报价-微坑盒-双插盒',
    boxId: 25,
    goodsId: 945,
    type: '专版报价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 4,
    actionName: '确认下单',
    channel: 501100,
    channelName: '专版报价-微坑盒-双插盒',
    boxId: 25,
    goodsId: 945,
    type: '专版报价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 5,
    actionName: '生成订单',
    channel: 501100,
    channelName: '专版报价-微坑盒-双插盒',
    boxId: 25,
    goodsId: 945,
    type: '专版报价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 6,
    actionName: '支付成功',
    channel: 501100,
    channelName: '专版报价-微坑盒-双插盒',
    boxId: 25,
    goodsId: 945,
    type: '专版报价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 1,
    actionName: '选择盒型',
    channel: 501200,
    channelName: '专版报价-微坑盒-锁底盒',
    boxId: 26,
    goodsId: 946,
    type: '专版报价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 2,
    actionName: '输入尺寸提交',
    channel: 501200,
    channelName: '专版报价-微坑盒-锁底盒',
    boxId: 26,
    goodsId: 946,
    type: '专版报价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 3,
    actionName: '加入购物车',
    channel: 501200,
    channelName: '专版报价-微坑盒-锁底盒',
    boxId: 26,
    goodsId: 946,
    type: '专版报价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 4,
    actionName: '确认下单',
    channel: 501200,
    channelName: '专版报价-微坑盒-锁底盒',
    boxId: 26,
    goodsId: 946,
    type: '专版报价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 5,
    actionName: '生成订单',
    channel: 501200,
    channelName: '专版报价-微坑盒-锁底盒',
    boxId: 26,
    goodsId: 946,
    type: '专版报价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 6,
    actionName: '支付成功',
    channel: 501200,
    channelName: '专版报价-微坑盒-锁底盒',
    boxId: 26,
    goodsId: 946,
    type: '专版报价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 1,
    actionName: '选择盒型',
    channel: 501300,
    channelName: '专版报价-微坑盒-一体成型盒',
    boxId: 28,
    goodsId: 948,
    type: '专版报价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 2,
    actionName: '输入尺寸提交',
    channel: 501300,
    channelName: '专版报价-微坑盒-一体成型盒',
    boxId: 28,
    goodsId: 948,
    type: '专版报价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 3,
    actionName: '加入购物车',
    channel: 501300,
    channelName: '专版报价-微坑盒-一体成型盒',
    boxId: 28,
    goodsId: 948,
    type: '专版报价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 4,
    actionName: '确认下单',
    channel: 501300,
    channelName: '专版报价-微坑盒-一体成型盒',
    boxId: 28,
    goodsId: 948,
    type: '专版报价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 5,
    actionName: '生成订单',
    channel: 501300,
    channelName: '专版报价-微坑盒-一体成型盒',
    boxId: 28,
    goodsId: 948,
    type: '专版报价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 6,
    actionName: '支付成功',
    channel: 501300,
    channelName: '专版报价-微坑盒-一体成型盒',
    boxId: 28,
    goodsId: 948,
    type: '专版报价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 1,
    actionName: '选择盒型',
    channel: 501400,
    channelName: '专版报价-微坑盒-吊口盒',
    boxId: 76,
    goodsId: 711,
    type: '专版报价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 2,
    actionName: '输入尺寸提交',
    channel: 501400,
    channelName: '专版报价-微坑盒-吊口盒',
    boxId: 76,
    goodsId: 711,
    type: '专版报价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 3,
    actionName: '加入购物车',
    channel: 501400,
    channelName: '专版报价-微坑盒-吊口盒',
    boxId: 76,
    goodsId: 711,
    type: '专版报价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 4,
    actionName: '确认下单',
    channel: 501400,
    channelName: '专版报价-微坑盒-吊口盒',
    boxId: 76,
    goodsId: 711,
    type: '专版报价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 5,
    actionName: '生成订单',
    channel: 501400,
    channelName: '专版报价-微坑盒-吊口盒',
    boxId: 76,
    goodsId: 711,
    type: '专版报价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 6,
    actionName: '支付成功',
    channel: 501400,
    channelName: '专版报价-微坑盒-吊口盒',
    boxId: 76,
    goodsId: 711,
    type: '专版报价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 1,
    actionName: '上传刀模',
    channel: 501900,
    channelName: '专版报价-微坑盒-自定义拼版',
    boxId: '',
    goodsId: '',
    type: '专版报价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 2,
    actionName: '输入尺寸提交',
    channel: 501900,
    channelName: '专版报价-微坑盒-自定义拼版',
    boxId: '',
    goodsId: '',
    type: '专版报价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 3,
    actionName: '加入购物车',
    channel: 501900,
    channelName: '专版报价-微坑盒-自定义拼版',
    boxId: '',
    goodsId: '',
    type: '专版报价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 4,
    actionName: '确认下单',
    channel: 501900,
    channelName: '专版报价-微坑盒-自定义拼版',
    boxId: '',
    goodsId: '',
    type: '专版报价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 5,
    actionName: '生成订单',
    channel: 501900,
    channelName: '专版报价-微坑盒-自定义拼版',
    boxId: '',
    goodsId: '',
    type: '专版报价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 6,
    actionName: '支付成功',
    channel: 501900,
    channelName: '专版报价-微坑盒-自定义拼版',
    boxId: '',
    goodsId: '',
    type: '专版报价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 1,
    actionName: '选择盒型',
    channel: 502100,
    channelName: '专版报价-精装盒-书型盒',
    boxId: 128,
    goodsId: 1616,
    type: '专版报价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 2,
    actionName: '输入尺寸提交',
    channel: 502100,
    channelName: '专版报价-精装盒-书型盒',
    boxId: 128,
    goodsId: 1616,
    type: '专版报价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 3,
    actionName: '加入购物车',
    channel: 502100,
    channelName: '专版报价-精装盒-书型盒',
    boxId: 128,
    goodsId: 1616,
    type: '专版报价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 4,
    actionName: '确认下单',
    channel: 502100,
    channelName: '专版报价-精装盒-书型盒',
    boxId: 128,
    goodsId: 1616,
    type: '专版报价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 5,
    actionName: '生成订单',
    channel: 502100,
    channelName: '专版报价-精装盒-书型盒',
    boxId: 128,
    goodsId: 1616,
    type: '专版报价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 6,
    actionName: '支付成功',
    channel: 502100,
    channelName: '专版报价-精装盒-书型盒',
    boxId: 128,
    goodsId: 1616,
    type: '专版报价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 1,
    actionName: '选择盒型',
    channel: 502200,
    channelName: '专版报价-精装盒-天包地天地盒',
    boxId: 137,
    goodsId: 1619,
    type: '专版报价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 2,
    actionName: '输入尺寸提交',
    channel: 502200,
    channelName: '专版报价-精装盒-天包地天地盒',
    boxId: 137,
    goodsId: 1619,
    type: '专版报价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 3,
    actionName: '加入购物车',
    channel: 502200,
    channelName: '专版报价-精装盒-天包地天地盒',
    boxId: 137,
    goodsId: 1619,
    type: '专版报价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 4,
    actionName: '确认下单',
    channel: 502200,
    channelName: '专版报价-精装盒-天包地天地盒',
    boxId: 137,
    goodsId: 1619,
    type: '专版报价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 5,
    actionName: '生成订单',
    channel: 502200,
    channelName: '专版报价-精装盒-天包地天地盒',
    boxId: 137,
    goodsId: 1619,
    type: '专版报价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 6,
    actionName: '支付成功',
    channel: 502200,
    channelName: '专版报价-精装盒-天包地天地盒',
    boxId: 137,
    goodsId: 1619,
    type: '专版报价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 1,
    actionName: '选择盒型',
    channel: 502300,
    channelName: '专版报价-精装盒-平口天地盒',
    boxId: 138,
    goodsId: 1620,
    type: '专版报价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 2,
    actionName: '输入尺寸提交',
    channel: 502300,
    channelName: '专版报价-精装盒-平口天地盒',
    boxId: 138,
    goodsId: 1620,
    type: '专版报价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 3,
    actionName: '加入购物车',
    channel: 502300,
    channelName: '专版报价-精装盒-平口天地盒',
    boxId: 138,
    goodsId: 1620,
    type: '专版报价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 4,
    actionName: '确认下单',
    channel: 502300,
    channelName: '专版报价-精装盒-平口天地盒',
    boxId: 138,
    goodsId: 1620,
    type: '专版报价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 5,
    actionName: '生成订单',
    channel: 502300,
    channelName: '专版报价-精装盒-平口天地盒',
    boxId: 138,
    goodsId: 1620,
    type: '专版报价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 6,
    actionName: '支付成功',
    channel: 502300,
    channelName: '专版报价-精装盒-平口天地盒',
    boxId: 138,
    goodsId: 1620,
    type: '专版报价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 5,
    actionName: '加入购物车',
    channel: 600000,
    channelName: '拼版报价-卡纸盒',
    boxId: '',
    goodsId: '',
    type: '拼版报价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 2,
    actionName: '确认下单',
    channel: 600000,
    channelName: '拼版报价-卡纸盒',
    boxId: '',
    goodsId: '',
    type: '拼版报价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 3,
    actionName: '生成订单',
    channel: 600000,
    channelName: '拼版报价-卡纸盒',
    boxId: '',
    goodsId: '',
    type: '拼版报价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 4,
    actionName: '支付成功',
    channel: 600000,
    channelName: '拼版报价-卡纸盒',
    boxId: '',
    goodsId: '',
    type: '拼版报价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 5,
    actionName: '加入购物车',
    channel: 601000,
    channelName: '拼版报价-坑纸内托',
    boxId: '',
    goodsId: '',
    type: '拼版报价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 2,
    actionName: '确认下单',
    channel: 601000,
    channelName: '拼版报价-坑纸内托',
    boxId: '',
    goodsId: '',
    type: '拼版报价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 3,
    actionName: '生成订单',
    channel: 601000,
    channelName: '拼版报价-坑纸内托',
    boxId: '',
    goodsId: '',
    type: '拼版报价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 4,
    actionName: '支付成功',
    channel: 601000,
    channelName: '拼版报价-坑纸内托',
    boxId: '',
    goodsId: '',
    type: '拼版报价'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 1,
    actionName: '确认下单',
    channel: 800000,
    channelName: '购物车-拼版购物车',
    boxId: '',
    goodsId: '',
    type: '购物车'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 2,
    actionName: '生成订单',
    channel: 800000,
    channelName: '购物车-拼版购物车',
    boxId: '',
    goodsId: '',
    type: '购物车'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 3,
    actionName: '支付成功',
    channel: 800000,
    channelName: '购物车-拼版购物车',
    boxId: '',
    goodsId: '',
    type: '购物车'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 1,
    actionName: '确认下单',
    channel: 801000,
    channelName: '购物车-买纸购物车',
    boxId: '',
    goodsId: '',
    type: '购物车'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 2,
    actionName: '生成订单',
    channel: 801000,
    channelName: '购物车-买纸购物车',
    boxId: '',
    goodsId: '',
    type: '购物车'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 3,
    actionName: '支付成功',
    channel: 801000,
    channelName: '购物车-买纸购物车',
    boxId: '',
    goodsId: '',
    type: '购物车'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 2,
    actionName: '设置页面',
    channel: 700000,
    channelName: '个人中心',
    boxId: '',
    goodsId: '',
    type: '个人中心'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 3,
    actionName: '拼版订单列表页',
    channel: 700000,
    channelName: '个人中心',
    boxId: '',
    goodsId: '',
    type: '个人中心'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 4,
    actionName: '待付款列表页',
    channel: 700000,
    channelName: '个人中心',
    boxId: '',
    goodsId: '',
    type: '个人中心'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 5,
    actionName: '待确认列表页',
    channel: 700000,
    channelName: '个人中心',
    boxId: '',
    goodsId: '',
    type: '个人中心'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 6,
    actionName: '待发货列表页',
    channel: 700000,
    channelName: '个人中心',
    boxId: '',
    goodsId: '',
    type: '个人中心'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 7,
    actionName: '买纸订单列表页',
    channel: 700000,
    channelName: '个人中心',
    boxId: '',
    goodsId: '',
    type: '个人中心'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 8,
    actionName: '印刷加工单列表页',
    channel: 700000,
    channelName: '个人中心',
    boxId: '',
    goodsId: '',
    type: '个人中心'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 1,
    actionName: '起点页面',
    channel: 701000,
    channelName: '个人中心-预存充值',
    boxId: '',
    goodsId: '',
    type: '个人中心'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 2,
    actionName: '账单页面',
    channel: 701000,
    channelName: '个人中心-预存充值',
    boxId: '',
    goodsId: '',
    type: '个人中心'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 3,
    actionName: '提交充值',
    channel: 701000,
    channelName: '个人中心-预存充值',
    boxId: '',
    goodsId: '',
    type: '个人中心'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 1,
    actionName: '起点页面',
    channel: 702000,
    channelName: '个人中心-优惠券',
    boxId: '',
    goodsId: '',
    type: '个人中心'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 2,
    actionName: '查询历史优惠券',
    channel: 702000,
    channelName: '个人中心-优惠券',
    boxId: '',
    goodsId: '',
    type: '个人中心'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 2,
    actionName: '提交联系人',
    channel: 900000,
    channelName: '印刷加工单',
    boxId: '',
    goodsId: '',
    type: '印刷加工单'
  },
  {
    appId: 2,
    appName: '拼一版小程序',
    actionId: 3,
    actionName: '上传文件',
    channel: 900000,
    channelName: '印刷加工单',
    boxId: '',
    goodsId: '',
    type: '印刷加工单'
  }
];
